trigger:
- main

pool:
  name: Default

steps:
- script: |
    ./mvnw -version
    ./mvnw clean package -DskipTests
  displayName: "Maven build"

- script: |
    docker version
    docker build -t petclinic:local .
  displayName: "Docker build"
